account_identifier: nssyklf-wo95251
pat_token: eyJraWQiOiIzOTMxOTkzMjk0MSIsImFsZyI6IkVTMjU2In0.eyJwIjoiMTUzNTkzMzQ4OjM5MzE5ODk2OTY1IiwiaXNzIjoiU0Y6MTAxNiIsImV4cCI6MTc5MzQxODAxNn0.06QMcnIOKUL4J1bgjl2ue-ALZy-nnlTvHbJFsavPZc7lgXNrsm6eM-1VisF-qqzW_x1vtZ9oY1ZhKe0aKzIGmw
role: ACCOUNTADMIN
